In [1]:
import geopandas as gp

In [2]:
import netCDF4 as nc

fn_w = '../raw_data/water-vapor-pressure_monthly-mean_bcc-csm1-1-m_rcp45_r1i1p1_1950-2100_v1.0.nc'
ds_w = nc.Dataset(fn_w)
print(ds_w)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    history: Wed Jun 23 08:31:25 2021: ncks -C -O -x -v height /data/public/global_data/cmip5/bcc-csm1-1-m/monthly/water-vapor-pressure_monthly-mean_bcc-csm1-1-m_rcp45_r1i1p1_1950-2100_v1.0.nc /data/public/global_data/cmip5/bcc-csm1-1-m/monthly/water-vapor-pressure_monthly-mean_bcc-csm1-1-m_rcp45_r1i1p1_1950-2100_v1.0_temp.nc
Fri Dec 18 08:10:58 2020: ncpdq -a time,latitude,longitude /tmp/tmpwm4a0b5m.nc_temp /tmp/tmpwm4a0b5m.nc
    Conventions: CF-1.7
    Institution: (C) VITO, Belgium
    References: See documentation for full references at https://climate.copernicus.eu/
    Contact: Please contact Copernicus User Support on the Copernicus Climate Change Service website (https://climate.copernicus.eu/)
    Version: v1
    Title: C3S D427 SIS Biodiversity / Bio-climate indicators / water-vapor-pressure / CMIP5 / rcp45 bcc-csm1-1-m r1i1p1 / bias-adjusted with ERA5 / 20-year month_000.5degree_global
    Source: CMIP5 dataset (rcp45 bcc-csm1-1-m r1i1p1) bias-adjusted to ERA5 by VITO
    Licence: ECMWF Copernicus licence 1.0
    NCO: netCDF Operators version 4.7.5 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)
    dimensions(sizes): latitude(348), longitude(720), time(1812)
    variables(dimensions): float64 latitude(latitude), float64 longitude(longitude), int64 time(time), float32 water-vapor-pressure(time, latitude, longitude)
    groups:

In [3]:
import xarray as xr

data_w= xr.open_dataset('../raw_data/water-vapor-pressure_monthly-mean_bcc-csm1-1-m_rcp45_r1i1p1_1950-2100_v1.0.nc')

In [4]:
data_w

<xarray.Dataset> Size: 2GB
Dimensions:               (latitude: 348, longitude: 720, time: 1812)
Coordinates:
  * latitude              (latitude) float64 3kB -89.75 -89.25 ... 83.25 83.75
  * longitude             (longitude) float64 6kB -179.8 -179.2 ... 179.2 179.8
  * time                  (time) datetime64[ns] 14kB 1950-01-01 ... 2100-12-01
Data variables:
    water-vapor-pressure  (time, latitude, longitude) float32 2GB ...
Attributes:
    history:      Wed Jun 23 08:31:25 2021: ncks -C -O -x -v height /data/pub...
    Conventions:  CF-1.7
    Institution:  (C) VITO, Belgium
    References:   See documentation for full references at https://climate.co...
    Contact:      Please contact Copernicus User Support on the Copernicus Cl...
    Version:      v1
    Title:        C3S D427 SIS Biodiversity / Bio-climate indicators / water-...
    Source:       CMIP5 dataset (rcp45 bcc-csm1-1-m r1i1p1) bias-adjusted to ...
    Licence:      ECMWF Copernicus licence 1.0
    NCO:          netCDF Operators version 4.7.5 (Homepage = http://nco.sf.ne...

In [5]:
df_w=data_w['water-vapor-pressure'].to_dataframe()
df_w

                               water-vapor-pressure
time       latitude longitude
1950-01-01 -89.75   -179.75                     NaN
                    -179.25                     NaN
                    -178.75                     NaN
                    -178.25                     NaN
                    -177.75                     NaN
...                                             ...
2100-12-01  83.75    177.75              239.446213
                     178.25              239.866425
                     178.75              240.231018
                     179.25              240.367294
                     179.75              240.531540

[454014720 rows x 1 columns]

In [6]:
df_w_reset = df_w.reset_index()

In [7]:
import pandas as pd

df_w_reset['time'] = pd.to_datetime(df_w_reset['time'])

# Truncate the DataFrame to start from the year 2015
df_w_reset_truncated = df_w_reset[df_w_reset['time'].dt.year >= 2015]

# Reset the index if needed
df_w_reset_truncated.reset_index(inplace=True)

In [8]:
df_w_reset_truncated

               index       time  latitude  longitude  water-vapor-pressure
0          195436800 2015-01-01    -89.75    -179.75                   NaN
1          195436801 2015-01-01    -89.75    -179.25                   NaN
2          195436802 2015-01-01    -89.75    -178.75                   NaN
3          195436803 2015-01-01    -89.75    -178.25                   NaN
4          195436804 2015-01-01    -89.75    -177.75                   NaN
...              ...        ...       ...        ...                   ...
258577915  454014715 2100-12-01     83.75     177.75            239.446213
258577916  454014716 2100-12-01     83.75     178.25            239.866425
258577917  454014717 2100-12-01     83.75     178.75            240.231018
258577918  454014718 2100-12-01     83.75     179.25            240.367294
258577919  454014719 2100-12-01     83.75     179.75            240.531540

[258577920 rows x 5 columns]

In [9]:
# min/max coordinate values for sample = 1000
# min_lon= -31.169029141664772
# max_lon = 32.611141887507934
# min_lat = 27.746311186883922
# max_lat = 69.04164438989706

In [10]:
# min/max coordinate values for all PA
min_lon= -32.30906837949666
max_lon = 34.071555485388096
min_lat = 27.658764598717514
max_lat = 70.01981302035634

In [11]:
df_w_filtered = df_w_reset_truncated[(df_w_reset_truncated["longitude"] >= min_lon) \
    & (df_w_reset_truncated["longitude"] <= max_lon) \
    & (df_w_reset_truncated["latitude"] >= min_lat) \
    & (df_w_reset_truncated["latitude"] <= max_lat)]
df_w_filtered

               index       time  latitude  longitude  water-vapor-pressure
169495     195606295 2015-01-01     27.75     -32.25            981.429260
169496     195606296 2015-01-01     27.75     -31.75            980.796631
169497     195606297 2015-01-01     27.75     -31.25            980.295776
169498     195606298 2015-01-01     27.75     -30.75            979.245117
169499     195606299 2015-01-01     27.75     -30.25            978.171997
...              ...        ...       ...        ...                   ...
258557463  453994263 2100-12-01     69.75      31.75            583.433472
258557464  453994264 2100-12-01     69.75      32.25            559.774536
258557465  453994265 2100-12-01     69.75      32.75            588.832031
258557466  453994266 2100-12-01     69.75      33.25            611.665649
258557467  453994267 2100-12-01     69.75      33.75            611.398926

[11666760 rows x 5 columns]

In [12]:
df_w_filtered.set_index('index', inplace=True)
#df_w_reset_truncated_filtered.drop(columns=df_w_reset_truncated_filtered.columns[0], inplace=True)
df_w_filtered

                time  latitude  longitude  water-vapor-pressure
index
195606295 2015-01-01     27.75     -32.25            981.429260
195606296 2015-01-01     27.75     -31.75            980.796631
195606297 2015-01-01     27.75     -31.25            980.295776
195606298 2015-01-01     27.75     -30.75            979.245117
195606299 2015-01-01     27.75     -30.25            978.171997
...              ...       ...        ...                   ...
453994263 2100-12-01     69.75      31.75            583.433472
453994264 2100-12-01     69.75      32.25            559.774536
453994265 2100-12-01     69.75      32.75            588.832031
453994266 2100-12-01     69.75      33.25            611.665649
453994267 2100-12-01     69.75      33.75            611.398926

[11666760 rows x 4 columns]

In [13]:
import pandas as pd

# Assuming df_t_reset_truncated is your initial DataFrame
# Ensure the time column is in datetime format
df_w_filtered.loc[:, 'time'] = pd.to_datetime(df_w_filtered['time'])

# Create a new column for the quarter start date
df_w_filtered.loc[:, 'quarter_start'] = df_w_filtered['time'].dt.to_period('Q').dt.start_time

# Group by latitude, longitude, and the quarter start date
# Calculate the mean temperature for each group
df_w_quarterly = df_w_filtered.groupby(['latitude', 'longitude', 'quarter_start']).agg({
    'water-vapor-pressure': 'mean'
})

# Rename columns for clarity
df_w_quarterly.rename(columns={'water-vapor-pressure': 'water-vapor-pressure_quarterly_mean'}, inplace=True)

/var/folders/db/1zlgknyx08v199b6h3k44t9m0000gn/T/ipykernel_9615/3612426942.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_w_filtered.loc[:, 'quarter_start'] = df_w_filtered['time'].dt.to_period('Q').dt.start_time

In [14]:
df_w_quarterly

                                  water-vapor-pressure_quarterly_mean
latitude longitude quarter_start
27.75    -32.25    2015-01-01                              958.008118
                   2015-04-01                             1019.887695
                   2015-07-01                             1111.479614
                   2015-10-01                             1061.997681
                   2016-01-01                              986.568909
...                                                               ...
69.75     33.75    2099-10-01                              665.558044
                   2100-01-01                              589.261719
                   2100-04-01                              638.465637
                   2100-07-01                              783.571960
                   2100-10-01                              617.109558

[3888920 rows x 1 columns]

In [15]:
df_w_quarterly.to_csv('../raw_data/water-vapor-pressure.csv')

: