**Imports**

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Load Data**

In [5]:
df= pd.read_csv("/home/alish/code/amelietatin/Predicting_land_cover/data/df_model_lc_2015_2024.csv")
df.drop("Unnamed: 0", axis=1, inplace=True)
data=df.copy()

In [6]:
data

,SITECODE,date,lon,lat,Bare Ground,Built Area,Crops,Flooded Vegetation,Grass,Shrub and Scrub,Snow and Ice,Trees,Water,temperature_quarterly_mean,precipitation_quarterly_mean,water-vapor-pressure_quarterly_mean,cloud-cover_quarterly_mean
0,AT1301000,2015-07-01,16.530699,48.172354,0.004731,0.306967,9.740933,0.434059,3.750812,1.101940,0.000000,79.647261,4.151655,18.86,2.788798e-08,942.75470,0.536892
1,AT1302000,2015-07-01,16.224738,48.176358,0.000079,0.450186,1.870178,0.062068,2.485236,0.504686,0.000000,94.372208,0.105224,18.12,3.174909e-08,948.60770,0.553719
2,AT1304000,2015-07-01,16.399310,48.313875,0.000000,3.427528,67.818286,0.180076,1.440462,1.265232,0.000000,24.646051,0.000000,18.12,3.174909e-08,948.60770,0.553719
3,AT2112000,2015-07-01,13.696092,46.591177,3.268027,0.178362,0.008970,0.550204,0.366961,13.011084,0.232740,82.268944,0.000000,13.15,5.000581e-08,891.69970,0.644521
4,AT2116000,2015-07-01,13.503149,46.603491,0.000000,0.845768,8.414334,0.328737,22.908775,0.229168,0.000000,58.175196,7.122431,13.15,5.000581e-08,891.69970,0.644521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22376,SE0820042,2024-04-01,22.080295,65.631796,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,96.868297,1.987538,0.000000,4.58,2.618655e-08,643.23303,0.658696
22377,SE0820295,2024-04-01,18.212619,67.150809,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,99.995652,0.000000,0.000000,0.02,3.101494e-08,562.88360,0.794345
22378,SE0820614,2024-04-01,20.350211,66.053867,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,99.987998,0.000000,0.000000,5.57,2.898485e-08,619.70465,0.720756
22379,SE0820615,2024-04-01,20.949495,66.373559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,99.995901,0.000000,0.000000,6.00,2.736414e-08,622.68720,0.716387
22380,SE0820616,2024-04-01,21.194107,66.652113,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,99.996812,0.000000,0.000000,4.72,3.003567e-08,608.81670,0.740763

In [7]:
data["date"].nunique()

36

## Data Preprocessing

In [8]:
# Convert date to datetime
data['date'] = pd.to_datetime(data['date'])

# Fill missing values (if any)
data.fillna(method='ffill', inplace=True)

# Normalize the features and targets
features = ['temperature_quarterly_mean', 'precipitation_quarterly_mean', 'water-vapor-pressure_quarterly_mean', 'cloud-cover_quarterly_mean']
targets = ['Bare Ground', 'Built Area', 'Crops', 'Flooded Vegetation', 'Grass', 'Shrub and Scrub', 'Snow and Ice', 'Trees', 'Water']

scaler_features = StandardScaler()
scaler_targets = StandardScaler()

data[features] = scaler_features.fit_transform(data[features])
data[targets] = scaler_targets.fit_transform(data[targets])

# Split into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, shuffle=False, stratify=None)

/tmp/ipykernel_1250/3500789452.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)

In [13]:
!pip install torch torchvision torchaudio

Collecting torch
  Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting torchvision
  Downloading torchvision-0.18.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio
  Downloading torchaudio-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting filelock (from torch)
  Downloading filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages (from torch) (4.12.0)
Collecting sympy (from torch)
  Downloading sympy-1.12.1-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: jinja2 in /home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages (from torch) (3.1.4)
Collecting fsspec (from torch)
  Downloading fsspec-2024.6.0-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.3.0 (from torch)
  Downloading triton-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy in /home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages (from torchvision) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages (from jinja2->torch) (2.1.5)
Collecting mpmath<1.4.0,>=1.1.0 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl (779.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.1/779.1 MB 2.5 MB/s eta 0:00:0000:0100:05
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 435.9 kB/s eta 0:00:000:0100:02
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Downloading triton-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (168.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.1/168.1 MB 3.5 MB/s eta 0:00:0000:0100:02
Downloading torchvision-0.18.0-cp310-cp310-manylinux1_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 3.9 MB/s eta 0:00:0000:0100:01
Downloading torchaudio-2.3.0-cp310-cp310-manylinux1_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 3.3 MB/s eta 0:00:0000:0100:01
Downloading filelock-3.14.0-py3-none-any.whl (12 kB)
Downloading fsspec-2024.6.0-py3-none-any.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.9/176.9 kB 3.7 MB/s eta 0:00:00a 0:00:01
Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.1 MB/s eta 0:00:0000:0100:01
Downloading sympy-1.12.1-py3-none-any.whl (5.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 2.2 MB/s eta 0:00:0000:0100:01
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl (21.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 4.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: mpmath, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, fsspec, filelock, triton, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchvision, torchaudio
Successfully installed filelock-3.14.0 fsspec-2024.6.0 mpmath-1.3.0 networkx-3.3 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 sympy-1.12.1 torch-2.3.0 torchaudio-2.3.0 torchvision-0.18.0 triton-2.3.0

## Prepare Data for Transformers

In [9]:
import torch
from torch.utils.data import Dataset, DataLoader

class TimeSeriesDataset(Dataset):
    def __init__(self, data, input_features, target_features, sequence_length):
        self.data = data
        self.input_features = input_features
        self.target_features = target_features
        self.sequence_length = sequence_length
    
    def __len__(self):
        return len(self.data) - self.sequence_length
    
    def __getitem__(self, idx):
        x = self.data[self.input_features].iloc[idx:idx + self.sequence_length].values
        y = self.data[self.target_features].iloc[idx + self.sequence_length].values
        return torch.tensor(x, dtype=torch.float32), torch.tensor(y, dtype=torch.float32)

sequence_length = 10
train_dataset = TimeSeriesDataset(train_data, features, targets, sequence_length)
test_dataset = TimeSeriesDataset(test_data, features, targets, sequence_length)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

## Define the Transformer Model

In [12]:
import torch.nn as nn
import torch.optim as optim

class TransformerModel(nn.Module):
    def __init__(self, input_dim, model_dim, num_heads, num_layers, output_dim, dropout=0.1):
        super(TransformerModel, self).__init__()
        self.model_dim = model_dim
        self.input_embedding = nn.Linear(input_dim, model_dim)
        self.positional_encoding = nn.Parameter(torch.zeros(1, sequence_length, model_dim))
        encoder_layer = nn.TransformerEncoderLayer(d_model=model_dim, nhead=num_heads, dropout=dropout)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc_out = nn.Linear(model_dim, output_dim)
    
    def forward(self, src):
        src = self.input_embedding(src) + self.positional_encoding
        output = self.transformer_encoder(src)
        output = self.fc_out(output[:, -1, :])  # Use the output of the last time step
        return output

input_dim = len(features)
model_dim = 64
num_heads = 4
num_layers = 2
output_dim = len(targets)

model = TransformerModel(input_dim, model_dim, num_heads, num_layers, output_dim)

# Training setup
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

/home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

## Train the Model

In [13]:
num_epochs = 20

model.train()
for epoch in range(num_epochs):
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
    print(f'Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}')

/home/alish/.pyenv/versions/3.10.6/envs/predicting_land_cover/lib/python3.10/site-packages/torch/autograd/graph.py:744: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Epoch 1/20, Loss: 1.2430
Epoch 2/20, Loss: 1.0635
Epoch 3/20, Loss: 1.2606
Epoch 4/20, Loss: 0.4825
Epoch 5/20, Loss: 1.5518
Epoch 6/20, Loss: 1.0574
Epoch 7/20, Loss: 0.7260
Epoch 8/20, Loss: 0.7597
Epoch 9/20, Loss: 1.1577
Epoch 10/20, Loss: 0.3134
Epoch 11/20, Loss: 0.7611
Epoch 12/20, Loss: 0.7163
Epoch 13/20, Loss: 0.4045
Epoch 14/20, Loss: 1.5009
Epoch 15/20, Loss: 0.4816
Epoch 16/20, Loss: 1.7936
Epoch 17/20, Loss: 1.8292
Epoch 18/20, Loss: 0.3494
Epoch 19/20, Loss: 0.2792
Epoch 20/20, Loss: 1.0665

## Evaluate the Model

In [14]:
model.eval()
test_loss = 0
with torch.no_grad():
    for inputs, targets in test_loader:
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        test_loss += loss.item()
print(f'Test Loss: {test_loss / len(test_loader):.4f}')

Test Loss: 0.9064

## Make Future Predictions

In [52]:
class TimeSeriesDataset(Dataset):
    def __init__(self, data, input_features, target_features=None, sequence_length=10, is_predict=False):
        self.data = data
        self.input_features = input_features
        self.target_features = target_features
        self.sequence_length = sequence_length
        self.is_predict = is_predict
    
    def __len__(self):
        return len(self.data) - self.sequence_length
    
    def __getitem__(self, idx):
        x = self.data[self.input_features].iloc[idx:idx + self.sequence_length].values
        x = torch.tensor(x, dtype=torch.float32)
        
        if self.is_predict:
            return x
        else:
            y = self.data[self.target_features].iloc[idx + self.sequence_length].values
            y = torch.tensor(y, dtype=torch.float32)
            return x, y

In [53]:
#importing and preproccessing the furture input data

In [ ]:
all_pa_future_values_2100

In [54]:
df_p= pd.read_csv("/home/alish/code/amelietatin/Predicting_land_cover/data/all_pa_future_values_2100.csv")
df_p

,SITECODE,lon,lat,quarter_start,temperature_quarterly_mean,precipitation_quarterly_mean,water-vapor-pressure_quarterly_mean,cloud-cover_quarterly_mean
0,IT5320009,13.292268,43.532192,2025-01-01,8.65,1.178506e-08,650.85570,0.500273
1,IT4050014,11.128795,44.319651,2025-01-01,5.11,1.629546e-08,606.74290,0.544266
2,IT4060015,12.256245,44.849636,2025-01-01,7.75,9.604958e-09,666.82480,0.515485
3,IT5330008,13.132352,42.878579,2025-01-01,2.14,2.546247e-08,538.16170,0.572809
4,IT4080001,11.801841,43.847954,2025-01-01,4.39,2.139190e-08,592.76886,0.588862
...,...,...,...,...,...,...,...,...
290923,AT2212000,14.183066,47.553708,2100-10-01,3.28,4.927227e-08,640.39496,0.644599
290924,AT3423000,9.701289,47.444386,2100-10-01,2.81,5.021011e-08,641.44490,0.616283
290925,AT2233000,15.549436,47.233696,2100-10-01,5.45,3.184268e-08,660.13380,0.641130
290926,SE0820616,21.194107,66.652113,2100-10-01,-4.13,1.396879e-08,519.12160,0.712890
290927,AT1301000,16.530699,48.172354,2100-10-01,7.48,1.811480e-08,679.59766,0.634030

In [92]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290928 entries, 0 to 290927
Data columns (total 8 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   SITECODE                             290928 non-null  object
 1   lon                                  280592 non-null  float64
 2   lat                                  280592 non-null  float64
 3   quarter_start                        290928 non-null  datetime64[ns]
 4   temperature_quarterly_mean           290928 non-null  float64
 5   precipitation_quarterly_mean         290928 non-null  float64
 6   water-vapor-pressure_quarterly_mean  290928 non-null  float64
 7   cloud-cover_quarterly_mean           290928 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 17.8+ MB

In [93]:
df_p.rename(columns={'quarter_start': 'date'}, inplace=True)

In [95]:
df_p= df_p[df_p['date'] == '2025-01-01']

In [99]:
# Assuming df is your DataFrame and n is the number of rows you want to keep
n = 624 # For example, let's say you want to keep 10 rows

df_p= df_p.iloc[:n]  # Keep only the first n rows

In [100]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
Index: 624 entries, 0 to 623
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SITECODE                             624 non-null    object
 1   lon                                  624 non-null    float64
 2   lat                                  624 non-null    float64
 3   date                                 624 non-null    datetime64[ns]
 4   temperature_quarterly_mean           624 non-null    float64
 5   precipitation_quarterly_mean         624 non-null    float64
 6   water-vapor-pressure_quarterly_mean  624 non-null    float64
 7   cloud-cover_quarterly_mean           624 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 43.9+ KB

In [101]:
# Normalize the features and targets
features_p = ['temperature_quarterly_mean', 'precipitation_quarterly_mean', 'water-vapor-pressure_quarterly_mean', 'cloud-cover_quarterly_mean']

In [103]:
scaler_features_p = StandardScaler()

In [104]:
df_p[features] = scaler_features.fit_transform(df_p[features])

/tmp/ipykernel_7570/891684074.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p[features] = scaler_features.fit_transform(df_p[features])

In [105]:
# Create a dataset for the new data
new_dataset = TimeSeriesDataset(df_p, features, sequence_length=sequence_length, is_predict=True)
new_loader = DataLoader(new_dataset, batch_size=32, shuffle=False)

# Use the model to make predictions on the new data
model.eval()
predictions = []
with torch.no_grad():
    for inputs in new_loader:
        outputs = model(inputs)
        predictions.append(outputs.numpy())

# Concatenate the predictions
predictions = np.concatenate(predictions, axis=0)

# Optionally, inverse transform the predictions to get them in the original scale
predictions = scaler_targets.inverse_transform(predictions)

In [106]:
predictions

array([[-7.66119063e-01,  1.94090605e-01,  3.94388413e+00, ...,
        -1.24974027e-01,  5.08875732e+01,  1.83025589e+01],
       [ 2.58686328e+00,  1.51587558e+00,  1.46661787e+01, ...,
         6.11557245e-01,  3.61539803e+01,  1.66397190e+01],
       [ 1.23657060e+00,  1.37709057e+00,  1.02372952e+01, ...,
        -1.65653959e-01,  4.55371017e+01,  1.89624405e+01],
       ...,
       [ 1.41511428e+00,  2.80192137e-01,  4.11053181e+00, ...,
         4.69328346e+01,  1.81901321e+01,  7.31198263e+00],
       [ 1.83538997e+00,  1.05102277e+00,  2.23913360e+00, ...,
         2.97799244e+01,  2.67477779e+01,  1.94754944e+01],
       [-6.02624238e-01,  1.10785365e-02, -2.24261498e+00, ...,
         7.47750320e+01,  1.06807785e+01,  9.41678333e+00]], dtype=float32)

In [107]:
predictions.shape

(614, 9)

In [108]:
test=predictions

In [109]:
targets = ['Bare Ground', 'Built Area', 'Crops', 'Flooded Vegetation', 'Grass', 'Shrub and Scrub', 'Snow and Ice', 'Trees', 'Water']
pred_df = pd.DataFrame(predictions, columns=targets)

In [110]:
pred_df

,Bare Ground,Built Area,Crops,Flooded Vegetation,Grass,Shrub and Scrub,Snow and Ice,Trees,Water
0,-0.766119,0.194091,3.943884,3.643610,7.427431,13.024722,-0.124974,50.887573,18.302559
1,2.586863,1.515876,14.666179,4.261152,6.553258,13.434013,0.611557,36.153980,16.639719
2,1.236571,1.377091,10.237295,3.756448,6.816466,8.670819,-0.165654,45.537102,18.962440
3,0.277972,1.180184,12.875554,2.788606,5.845255,5.061635,-0.268092,51.925537,16.372692
4,1.896538,1.701235,13.527433,4.026463,5.360618,14.286880,0.192259,30.792482,21.407534
...,...,...,...,...,...,...,...,...,...
609,-0.539707,0.411097,2.877422,3.100055,11.275384,6.180788,0.218433,60.454391,12.188113
610,1.318872,0.877010,1.711568,0.630708,-0.222878,9.043363,42.836498,22.848162,15.001291
611,1.415114,0.280192,4.110532,-0.143353,1.292660,2.319513,46.932835,18.190132,7.311983
612,1.835390,1.051023,2.239134,0.947489,0.127499,11.779229,29.779924,26.747778,19.475494
613,-0.602624,0.011079,-2.242615,-0.198793,0.075089,3.584172,74.775032,10.680779,9.416783

In [112]:
# Extracting the relevant SITECODE and date information
sitecode_series = []
date_series = []

for idx in range(len(df_p) - sequence_length):
    sitecode_series.append(df_p['SITECODE'].iloc[idx + sequence_length])
    date_series.append(df_p['date'].iloc[idx + sequence_length])

# Creating DataFrame for metadata
meta_df = pd.DataFrame({
    'SITECODE': sitecode_series,
    'date': date_series
})

# Combining predictions with metadata
result_df = pd.concat([meta_df.reset_index(drop=True), pred_df.reset_index(drop=True)], axis=1)

# Sorting by SITECODE and quarter_start
result_df.sort_values(by=['SITECODE', 'date'], inplace=True)

# Resetting index for better readability
result_df.reset_index(drop=True, inplace=True)

# Display the resulting DataFrame
result_df

,SITECODE,date,Bare Ground,Built Area,Crops,Flooded Vegetation,Grass,Shrub and Scrub,Snow and Ice,Trees,Water
0,CY3000008,2025-01-01,0.345829,0.432522,1.512310,1.429563,10.264278,7.035055,2.268138,33.805573,31.103014
1,CY4000004,2025-01-01,1.208799,1.420116,11.209067,2.323092,5.790061,5.264836,1.435536,50.631985,13.761895
2,CY4000024,2025-01-01,0.351245,1.847695,14.452706,1.520967,4.820847,8.450259,-1.471874,58.257442,9.771082
3,CY5000005,2025-01-01,-0.556529,0.018468,0.622534,3.396560,10.316833,4.116656,-0.828454,69.751511,10.265757
4,DE1121391,2025-01-01,2.301013,2.094562,8.199068,2.194527,3.381576,9.385427,2.140548,35.979694,32.638039
...,...,...,...,...,...,...,...,...,...,...,...
609,SE0710166,2025-01-01,0.469707,0.533998,3.403160,2.435643,8.686646,6.823555,-0.103032,58.210415,13.031007
610,SE0810051,2025-01-01,1.107128,1.244721,11.862308,2.660056,4.309787,8.641632,-0.911108,39.343761,28.541922
611,SE0810443,2025-01-01,-0.221831,0.257135,-0.988581,0.132215,-0.224958,6.343356,60.869572,17.872009,10.808828
612,SE0810521,2025-01-01,4.170357,1.896729,13.764013,4.479132,2.617584,15.467252,-0.438645,45.389069,9.517423
613,SE0820108,2025-01-01,-0.165894,0.296718,2.885700,4.901579,12.614558,4.387643,-0.910965,61.003021,11.150412

In [113]:
result_df["Crops"].count()

614

In [ ]:
# Assuming df is your DataFrame containing the data

# Filter rows with the same SITECODE and quarter_start
filtered_df = df.groupby(['SITECODE', 'quarter_start']).filter(lambda x: len(x) > 1)

# Drop duplicate rows, keeping only the first occurrence
filtered_df = filtered_df.drop_duplicates(subset=['SITECODE', 'quarter_start'], keep='first')

# Now, filtered_df contains rows with unique SITECODE and quarter_start, and duplicates have been removed

In [79]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
# Extract the target columns (e.g., land cover classes) from the DataFrames
target_columns = ['Bare Ground', 'Built Area', 'Crops', 'Flooded Vegetation', 'Grass', 'Shrub and Scrub', 'Snow and Ice', 'Trees', 'Water']
true_values = data[target_columns].values
predicted_values = result_df[target_columns].values

# Calculate Mean Absolute Error (MAE) for each target column
mae_per_class = mean_absolute_error(true_values, predicted_values, multioutput='raw_values')

# Calculate Root Mean Squared Error (RMSE) for each target column
mse_per_class = mean_squared_error(true_values, predicted_values, multioutput='raw_values')
rmse_per_class = np.sqrt(mse_per_class)

# Display the evaluation metrics for each target column
evaluation_metrics = pd.DataFrame({
    'Target Class': target_columns,
    'MAE': mae_per_class,
    'RMSE': rmse_per_class
})
print("Evaluation Metrics:")
print(evaluation_metrics)

ValueError: Found input variables with inconsistent numbers of samples: [22381, 290918]

In [89]:
temp1= df_p[df_p["SITECODE"=="IT4060015"]]

KeyError: False